### ISSUE TITLE
Extent reports 4.1.5 Not uploading Images?

### ISSUE THREAD

**Issue by awang101** [extent-framework/extentreports-java#163] opened 2020-05-20 20:17 UTC
Hi,

Using extent reports 4.1.5 and using JsonFormatter json = new JsonFormatter("target/test.json"); 

For our second suite, it seems like our images / screenshots are not showing up, is there anyway to fix that?

Thank you

**Comment by anshooarora** [comment] 2020-05-20 22:16
Duplicate of #161

**Closed by anshooarora** 2020-05-20 22:16 UTC
Labels: duplicate
