### ISSUE TITLE
ExtentReports with Cucumber ends the program

### ISSUE THREAD

**Issue by jchristheodore** [extent-framework/extentreports-java#69] opened 2019-03-26 13:56 UTC
Extent report when used with cucumber feature files and there is a step error. It ends the java program and doesn't call @afterClass/@after.

**Comment by foursyth** [comment] 2019-03-27 18:08
Can you share the Cucumber/ExtentReports/adapter versions?

**Comment by virenv** [comment] 2019-04-14 06:37
@jchristheodore : Because of lack of information, I am closing the issue. Please reopen it by adding more details to reproduce the issue.

**Closed by virenv** 2019-04-14 06:37 UTC
