### ISSUE TITLE
Freemarker templete error (Extent-report-version 4.0.9)

### ISSUE THREAD

**Issue by akumarpeddle** [extent-framework/extentreports-java#101] opened 2019-11-21 10:35 UTC
@Test(priority = 1)
	public void testLocalFolderCreationOrderMultipleTries(Method method) throws IOException {
		ExtentHtmlReporter html;

		html = new ExtentHtmlReporter("target/Extent.html");

		extent.attachReporter(html);
		
		ExtentTest parent = extent.createTest("feature");
		ExtentTest child = parent.createNode("Scenario");
		child.log(Status.FAIL, "Hello");

	}

this is the code i an running in my local after downloading the code base of extentreports-java

StackTrace:
SEVERE: Error executing FreeMarker template
FreeMarker template error:
The following has evaluated to null or missing:
==> firstTest.nodeContext  [in template "v3html/v3-html-index.ftl" at line 20, column 50]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #assign bddReport = (firstTest.hasChi...  [in template "v3html/v3-html-index.ftl" at line 20, column 1]
----

Java stack trace (for programmers):
as well as for v3-html-standard.ftl the same error is coming
test.nodeContext is coming as null

**Comment by anshooarora** [comment] 2019-12-24 05:11
@akumarpeddle I am unable to reproduce this with `v4.0.9`.  What version are you using?

**Comment by akumarpeddle** [comment] 2019-12-24 07:35
I am using v4.0.9 version

**Comment by anshooarora** [comment] 2019-12-24 18:13
Are you creating a BDD report?  You must supply the Gherkin classes to create a BDD-style report.  See here as an example:  http://extentreports.com/docs/versions/4/java/#create-bdd-tests

**Comment by akumarpeddle** [comment] 2019-12-26 04:03
I don't need bdd type for normal execution i want node level reporting

**Comment by anshooarora** [comment] 2019-12-26 06:13
Please share the complete ExtentReports snippet.  Its hard to know what's going on with the provided information..

**Comment by akumarpeddle** [comment] 2019-12-26 06:22
![Report](https://user-images.githubusercontent.com/58031165/71461522-1fe7f000-27d6-11ea-96ed-f96dcea56deb.jpg)

**Comment by anshooarora** [comment] 2019-12-26 06:23
Can you share the code snippet?

**Comment by casalribeiro** [comment] 2019-12-30 15:59
I'm getting the same error.
Maybe it's related to the change of `getNodeContext()` to `getChildrenNodes()`.
I'm getting this error in:
`The following has evaluated to null or missing:
==> firstTest.nodeContext  [in template "v3html/v3-html-index.ftl" at line 20, column 50]`

I'm using 4.0.10 SNAPSHOT

**Comment by anshooarora** [comment] 2019-12-31 00:17
@akumarpeddle  @casalribeiro 

Thanks, I will fix this in the upcoming release

**Comment by anshooarora** [comment] 2020-01-02 00:07
All - please try with `4.10.0-SNAPSHOT`.  Sources [here](https://github.com/extent-framework/extentreports-java/tree/4.10.0)

**Comment by casalribeiro** [comment] 2020-01-02 14:23
Had to make some changes on my side to have it working with my previous code.
It's working fine now although I got an error building the project in `com/aventstack/extentreports/mediastorage/KlovMediaStorageHandler.java`

Other than that no problem at all 👍

**Comment by anshooarora** [comment] 2020-01-02 18:25
@casalribeiro You can use the snapshot directly from:

```
<dependency>
	<groupId>com.aventstack</groupId>
	<artifactId>extentreports</artifactId>
	<version>4.1.0-SNAPSHOT</version>
</dependency>
```

Can you share the error?

**Comment by casalribeiro** [comment] 2020-01-03 12:31
It's working perfectly from what I can tell.

I notice a difference between the sources you provided and the Maven dependency one.
In the sources I got two deprecated classes:
`com.aventstack.extentreports.reporter.ExtentHtmlReporter`
`com.aventstack.extentreports.reporter.ExtentLoggerReporter`
and when I imported through Maven I didn't get that info.

Regarding the error I got building the project, the [Test class](https://github.com/extent-framework/extentreports-java/blob/4.10.0/src/main/java/com/aventstack/extentreports/model/Test.java) is not implementing `BasicMongoReportElement`

error in [KlovMediaStorageHandler.java](https://github.com/extent-framework/extentreports-java/blob/b7b62c32dd5b9b429ac6e9aedda0eef108a5f2e2/src/main/java/com/aventstack/extentreports/mediastorage/KlovMediaStorageHandler.java#L35) `Error:(35, 27) java: incomparable types: java.lang.Class<capture#1 of ? extends com.aventstack.extentreports.model.BasicMongoReportElement> and java.lang.Class<com.aventstack.extentreports.model.Test>`

**Comment by anshooarora** [comment] 2020-01-04 05:36
@casalribeiro this has been fixed in the latest snapshot.

**Comment by anshooarora** [comment] 2020-01-06 00:29
Closing as this being included in milestone release 4.10.0.

**Closed by anshooarora** 2020-01-06 00:29 UTC
Labels: bug

**Comment by casalribeiro** [comment] 2020-01-06 13:43
Hi @anshooarora , I saw you merged this into master today.
I changed my pom to load 4.1.0. instead of the snapshot version but I'm getting a freemarker problem. It's loading freemarker version `<version>2.3.23</version>` instead of `<version>2.3.29</version>`
I've deleted previous downloaded dependencies, cleaned the project, rebuild it, imported all libraries again but it keeps importing that version. 
I browsed the repository and it shows the wrong version also:
[sonatype repo](https://oss.sonatype.org/service/local/repositories/releases/archive/com/aventstack/extentreports/4.1.0/extentreports-4.1.0.jar/!/META-INF/maven/com.aventstack/extentreports/pom.xml)

**Comment by anshooarora** [comment] 2020-01-06 18:21
@casalribeiro Looks like I used pom.xml from an older commit to deploy the release.  Please try with version `4.1.1`.

**Comment by casalribeiro** [comment] 2020-01-08 11:41
> @casalribeiro Looks like I used pom.xml from an older commit to deploy the release. Please try with version `4.1.1`.

Thanks, it's working just fine 👍

**Comment by singhik** [comment] 2020-06-29 19:16
@anshooarora : I am getting this Exception with 4.1.1 
	<dependency>
	    <groupId>com.aventstack</groupId>
	    <artifactId>extentreports</artifactId>
	    <version>4.1.1</version>	   
    </dependency>

Exception Message ::

freemarker.log._JULLoggerFactory$JULLogger error
SEVERE: Error executing FreeMarker template
FreeMarker template error:
The following has evaluated to null or missing:
==> report.systemInfoMap[info]  [in template "Extent.ftl" at line 193, column 95]

----
Tip: It's the final [] step that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${report.systemInfoMap[info]}  [in template "Extent.ftl" at line 193, column 93]
----

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
	at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:479)
	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:401)
	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:370)
	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
	at freemarker.core.Environment.visit(Environment.java:367)
	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:291)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:643)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:331)
	at freemarker.core.Environment.visit(Environment.java:337)
	at freemarker.core.Environment.process(Environment.java:310)
	at freemarker.template.Template.process(Template.java:383)
	at com.relevantcodes.extentreports.HTMLReporter.flush(HTMLReporter.java:173)
	at com.relevantcodes.extentreports.Report.flush(Report.java:468)
	at com.relevantcodes.extentreports.ExtentReports.flush(ExtentReports.java:900)
	at evs.EVSRESTAPIAUTOMATION.EVSRESTAPI.evsRestAPI(EVSRESTAPI.java:257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by singhik** [comment] 2020-06-29 19:24
@anshooarora : If i remove 'extent.flush()' the error goes but the Extent Report in NOT generated ? Can you please align on any possible reasoning and solution ?

**Comment by anshooarora** [comment] 2020-06-29 19:32
@singhik Please use the latest version with ExtentSparkReporter and let me know if you still encounter this?

**Comment by singhik** [comment] 2020-06-29 19:38
@anshooarora : Hi, unable to find any maven dependancy for ExtentSparkReporter ,can you please provide the dependency xml form ? 

![image](https://user-images.githubusercontent.com/36314371/86048465-90d6c180-ba1e-11ea-97b4-4cf77752b16c.png)

**Comment by singhik** [comment] 2020-06-29 19:44
@anshooarora :: Hi, Currently my POM in configured per below for Extent report version 4.1.6 ::

![image](https://user-images.githubusercontent.com/36314371/86049049-76e9ae80-ba1f-11ea-95e3-b079a848740d.png)

**Comment by anshooarora** [comment] 2020-06-29 19:46
You need the following:

```
<dependency>
  <groupId>com.aventstack</groupId>
  <artifactId>extentreports</artifactId>
  <version>4.1.7</version>
</dependency>
```

and:

```
ExtentSparkReporter spark = new ExtentSparkReporter("target/Spark/Index.html");
```

**Comment by singhik** [comment] 2020-06-29 20:33
@anshooarora : Hi, I have implemented above changes and instantiated all my respective objects for ExtentSparkReporter()   but i still get the Same **Failure** as before, below are the logs :: 

Jun 29, 2020 4:30:35 PM freemarker.log._JULLoggerFactory$JULLogger error
SEVERE: Error executing FreeMarker template
FreeMarker template error:
The following has evaluated to null or missing:
==> report.systemInfoMap[info]  [in template "Extent.ftl" at line 193, column 95]

----
Tip: It's the final [] step that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${report.systemInfoMap[info]}  [in template "Extent.ftl" at line 193, column 93]
----

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
	at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:479)
	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:401)
	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:370)
	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
	at freemarker.core.Environment.visit(Environment.java:367)
	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:291)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:643)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:331)
	at freemarker.core.Environment.visit(Environment.java:337)
	at freemarker.core.Environment.process(Environment.java:310)
	at freemarker.template.Template.process(Template.java:383)
	at com.relevantcodes.extentreports.HTMLReporter.flush(HTMLReporter.java:173)
	at com.relevantcodes.extentreports.Report.flush(Report.java:468)
	at com.relevantcodes.extentreports.ExtentReports.flush(ExtentReports.java:900)
	at evs.EVSRESTAPIAUTOMATION.EVSRESTAPI.endreport(EVSRESTAPI.java:284)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.afterRun(TestRunner.java:725)
	at org.testng.TestRunner.run(TestRunner.java:509)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by singhik** [comment] 2020-06-29 20:36
@anshooarora : Can you please help me with that error ? Is there any other way for the Report to get generated with out using Extent.flush() ?  As that line of code is causing those exceptions but if  removed, the Report does not generate  :(

**Comment by anshooarora** [comment] 2020-06-29 20:39
Are you using Spark? Or HTML? What are you attaching to ExtentReports?

**Comment by singhik** [comment] 2020-06-29 20:46
@anshooarora : Hi, i am appending it with HTML form , below is the split code snippet for reference  ::

ExtentSparkReporter sparkReporter;
ExtentReports extentReport;

String reportPath = System.getProperty("user.dir")+"/test-output/"+"API"+".html";

sparkReporter = new ExtentSparkReporter(reportPath);
sparkReporter.config().setDocumentTitle("EVS REST API AUTOMATION");
sparkReporter.config().setReportName("EVS REST API");
sparkReporter.config().setTheme(com.aventstack.extentreports.reporter.configuration.Theme.DARK);
extentReport = new ExtentReports(reportPath);
extentReport.addSystemInfo("Host Name", "Local");
extentReport.addSystemInfo("Environment", "Dev");
extentReport.loadConfig(new File(System.getProperty("user.dir")+"\\extent-config.xml"));



test = extentReport.startTest(""+apiName);
test.log(LogStatus.PASS,"EXPECTED STATUS CODE - "+statusCodeExpected + "   "+"ACTUAL STATUS CODE - "+actualstatusCode);



@AfterTest
public void endreport()
{
extentReport.flush();

}

**Comment by anshooarora** [comment] 2020-06-29 22:18
You are mixing ExtentReports 3 and 4 :)

Just use 4 in your pom or gradle build.

**Comment by singhik** [comment] 2020-06-30 00:24
@anshooarora : Hi, I did amend my code after you asked me to use SparkExtentReporter, before that i was using  code for extent Report in entirety and was still getting that Exception, the issue appears to be with Extent.flush() , is there an alternative to that Thread usage of Extent.flush() ?

**Comment by anshooarora** [comment] 2020-06-30 22:48
Flush writes the report and the only time the template is loaded during flush that is why you see this error there.  

It also seems you are mixing usage between multiple major versions.  If you intend to use version 4, please make sure you have correct usage after referring to the docs. 

In case the issue persists, you can create a new ticket with your `pom.xml` and ExtentReports instantiation code.
