### ISSUE TITLE
Unable to format the JSON String in report.

### ISSUE THREAD

**Issue by sumanguduru** [extent-framework/extentreports-java#193] opened 2020-06-22 17:52 UTC
Version 4.1.6
**((ExtentTest)stepTest.get()).info(MarkupHelper.createCodeBlock(json, CodeLanguage.JSON));**

When i use the above code its printing message as below
<div class='json-tree' id='code-block-json-1'></div>
	<script>
		function jsonTreeCreate1() { 
			document.getElementById('code-block-json-1').innerHTML = JSONTree.create({  "id" : 73,  "number" : "800090803",  "id" : "Tk-5010",  "name" : "GAP Inc",  "tad" : "91-1234587",  "reasonDescription" : "TEST - Activat",  "statusModifiedDate" : "2020-06-02T19:50:28.116",  "status" : "ACTIVE",  "address" : {    "street" : "2 Folsom St",    "address2" : "",    "address3" : "",    "city" : "San Francisco",    "state" : "CA",    "zip" : "94105",    "country" : "USA"  }}); 
		}
		jsonTreeCreate1();
	</script>

**Comment by anshooarora** [comment] 2020-06-24 07:12
Duplicate of https://github.com/extent-framework/extentreports-java/issues/147, fixed in version 5.0.0-SNAPSHOT.

I will include this in the next v4 release.

**Closed** 2020-06-24 07:25 UTC
Labels: bug
